# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: params.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='params.proto',
  package='exportParams',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cparams.proto\x12\x0c\x65xportParams\"a\n\x0c\x45xportParams\x12\x0e\n\x06IntVal\x18\x01 \x01(\x05\x12\x10\n\x08\x46loatVal\x18\x02 \x01(\x02\x12\x16\n\x0e\x41rrayOfStrings\x18\x03 \x03(\t\x12\x17\n\x0b\x41rrayOfData\x18\x04 \x03(\x02\x42\x02\x10\x01\x62\x06proto3')
)




_EXPORTPARAMS = _descriptor.Descriptor(
  name='ExportParams',
  full_name='exportParams.ExportParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IntVal', full_name='exportParams.ExportParams.IntVal', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FloatVal', full_name='exportParams.ExportParams.FloatVal', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ArrayOfStrings', full_name='exportParams.ExportParams.ArrayOfStrings', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ArrayOfData', full_name='exportParams.ExportParams.ArrayOfData', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['ExportParams'] = _EXPORTPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExportParams = _reflection.GeneratedProtocolMessageType('ExportParams', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTPARAMS,
  __module__ = 'params_pb2'
  # @@protoc_insertion_point(class_scope:exportParams.ExportParams)
  ))
_sym_db.RegisterMessage(ExportParams)


_EXPORTPARAMS.fields_by_name['ArrayOfData']._options = None
# @@protoc_insertion_point(module_scope)
