// Code generated by protoc-gen-go. DO NOT EDIT.
// source: params.proto

package exportParams

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExportParams struct {
	IntVal               *int32    `protobuf:"varint,1,opt,name=IntVal" json:"IntVal,omitempty"`
	FloatVal             *float32  `protobuf:"fixed32,2,opt,name=FloatVal" json:"FloatVal,omitempty"`
	ArrayOfData          []float32 `protobuf:"fixed32,4,rep,packed,name=ArrayOfData" json:"ArrayOfData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ExportParams) Reset()         { *m = ExportParams{} }
func (m *ExportParams) String() string { return proto.CompactTextString(m) }
func (*ExportParams) ProtoMessage()    {}
func (*ExportParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_params_31a0d92d9cdf1682, []int{0}
}
func (m *ExportParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportParams.Unmarshal(m, b)
}
func (m *ExportParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportParams.Marshal(b, m, deterministic)
}
func (dst *ExportParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportParams.Merge(dst, src)
}
func (m *ExportParams) XXX_Size() int {
	return xxx_messageInfo_ExportParams.Size(m)
}
func (m *ExportParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportParams.DiscardUnknown(m)
}

var xxx_messageInfo_ExportParams proto.InternalMessageInfo

func (m *ExportParams) GetIntVal() int32 {
	if m != nil && m.IntVal != nil {
		return *m.IntVal
	}
	return 0
}

func (m *ExportParams) GetFloatVal() float32 {
	if m != nil && m.FloatVal != nil {
		return *m.FloatVal
	}
	return 0
}

func (m *ExportParams) GetArrayOfData() []float32 {
	if m != nil {
		return m.ArrayOfData
	}
	return nil
}

func init() {
	proto.RegisterType((*ExportParams)(nil), "exportParams.ExportParams")
}

func init() { proto.RegisterFile("params.proto", fileDescriptor_params_31a0d92d9cdf1682) }

var fileDescriptor_params_31a0d92d9cdf1682 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2c, 0x4a,
	0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0xad, 0x28, 0xc8, 0x2f, 0x2a,
	0x09, 0x00, 0x8b, 0x29, 0x65, 0x70, 0xf1, 0xb8, 0x22, 0xf1, 0x85, 0xc4, 0xb8, 0xd8, 0x3c, 0xf3,
	0x4a, 0xc2, 0x12, 0x73, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xa0, 0x3c, 0x21, 0x29, 0x2e,
	0x0e, 0xb7, 0x9c, 0xfc, 0x44, 0xb0, 0x0c, 0x13, 0x50, 0x86, 0x29, 0x08, 0xce, 0x17, 0x52, 0xe1,
	0xe2, 0x76, 0x2c, 0x2a, 0x4a, 0xac, 0xf4, 0x4f, 0x73, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x51, 0x60,
	0xd6, 0x60, 0x72, 0x62, 0x12, 0x60, 0x0c, 0x42, 0x16, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc7,
	0x05, 0x2a, 0xb4, 0x86, 0x00, 0x00, 0x00,
}
